env_name: 'Ant-v4'
act_type: 'ReLU'
n_steps: 1e8
g: 0.99
lm: 0.95
u_epi_ups: 0
bs: 2048
n_itrs: 10
n_slices: 16
lr: 0.0001
h_dim: [256, 256]
u_adv_scl: 1
clip_eps: 0.2
ob_norm: 0
rew_norm: 0
wd: 0
dir: 'data/ant/upgd_full/'
to_log: ['pol_features_activity', 'pol_weights', 'val_weights', 'stable_rank', 'weight_change']
label: 'UPGD (Full)'

# UPGD optimizer settings
optimizer_type: 'upgd'
beta_utility: 0.9999
sigma: 0.0
gating_mode: 'full'
non_gated_scale: 0.5
gating_fn: 'sigmoid'
max_grad_norm: 1.0
eps: 1e-5
